sudo: required

services:
  - docker

before_install:
  - docker run -d --name rascal-rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
  - sleep 5
  - curl --retry 20 --retry-delay 1 http://localhost:15672
language: node_js

node_js:
  - "6"
  - "8"
  - "10"
  - "11"
