sudo: required

services:
  - docker

before_install:
  - docker run -d --name rascal-rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
  - sleep 5
language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "10"
